//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("DBProyectoModel", "FK_CO_LOG_SYS_CO_USUARIO1", "CO_USUARIO", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(WebApplication1.Modelos.CO_USUARIO), "CO_LOG_SYS", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(WebApplication1.Modelos.CO_LOG_SYS), true)]

#endregion

namespace WebApplication1.Modelos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class DBProyectoEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto DBProyectoEntities usando la cadena de conexión encontrada en la sección 'DBProyectoEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public DBProyectoEntities() : base("name=DBProyectoEntities", "DBProyectoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DBProyectoEntities.
        /// </summary>
        public DBProyectoEntities(string connectionString) : base(connectionString, "DBProyectoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto DBProyectoEntities.
        /// </summary>
        public DBProyectoEntities(EntityConnection connection) : base(connection, "DBProyectoEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CO_LOG_SYS> CO_LOG_SYS
        {
            get
            {
                if ((_CO_LOG_SYS == null))
                {
                    _CO_LOG_SYS = base.CreateObjectSet<CO_LOG_SYS>("CO_LOG_SYS");
                }
                return _CO_LOG_SYS;
            }
        }
        private ObjectSet<CO_LOG_SYS> _CO_LOG_SYS;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<CO_USUARIO> CO_USUARIO
        {
            get
            {
                if ((_CO_USUARIO == null))
                {
                    _CO_USUARIO = base.CreateObjectSet<CO_USUARIO>("CO_USUARIO");
                }
                return _CO_USUARIO;
            }
        }
        private ObjectSet<CO_USUARIO> _CO_USUARIO;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;

        #endregion
        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CO_LOG_SYS. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCO_LOG_SYS(CO_LOG_SYS cO_LOG_SYS)
        {
            base.AddObject("CO_LOG_SYS", cO_LOG_SYS);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet CO_USUARIO. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCO_USUARIO(CO_USUARIO cO_USUARIO)
        {
            base.AddObject("CO_USUARIO", cO_USUARIO);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet sysdiagrams. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }

        #endregion
    }
    

    #endregion
    
    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBProyectoModel", Name="CO_LOG_SYS")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CO_LOG_SYS : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CO_LOG_SYS.
        /// </summary>
        /// <param name="cO_IDLOG">Valor inicial de la propiedad CO_IDLOG.</param>
        public static CO_LOG_SYS CreateCO_LOG_SYS(global::System.Int32 cO_IDLOG)
        {
            CO_LOG_SYS cO_LOG_SYS = new CO_LOG_SYS();
            cO_LOG_SYS.CO_IDLOG = cO_IDLOG;
            return cO_LOG_SYS;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 CO_IDLOG
        {
            get
            {
                return _CO_IDLOG;
            }
            set
            {
                if (_CO_IDLOG != value)
                {
                    OnCO_IDLOGChanging(value);
                    ReportPropertyChanging("CO_IDLOG");
                    _CO_IDLOG = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CO_IDLOG");
                    OnCO_IDLOGChanged();
                }
            }
        }
        private global::System.Int32 _CO_IDLOG;
        partial void OnCO_IDLOGChanging(global::System.Int32 value);
        partial void OnCO_IDLOGChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CO_IDUSUARIO
        {
            get
            {
                return _CO_IDUSUARIO;
            }
            set
            {
                OnCO_IDUSUARIOChanging(value);
                ReportPropertyChanging("CO_IDUSUARIO");
                _CO_IDUSUARIO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CO_IDUSUARIO");
                OnCO_IDUSUARIOChanged();
            }
        }
        private Nullable<global::System.Int32> _CO_IDUSUARIO;
        partial void OnCO_IDUSUARIOChanging(Nullable<global::System.Int32> value);
        partial void OnCO_IDUSUARIOChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CO_FECHA_ING
        {
            get
            {
                return _CO_FECHA_ING;
            }
            set
            {
                OnCO_FECHA_INGChanging(value);
                ReportPropertyChanging("CO_FECHA_ING");
                _CO_FECHA_ING = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CO_FECHA_ING");
                OnCO_FECHA_INGChanged();
            }
        }
        private Nullable<global::System.DateTime> _CO_FECHA_ING;
        partial void OnCO_FECHA_INGChanging(Nullable<global::System.DateTime> value);
        partial void OnCO_FECHA_INGChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CO_PC
        {
            get
            {
                return _CO_PC;
            }
            set
            {
                OnCO_PCChanging(value);
                ReportPropertyChanging("CO_PC");
                _CO_PC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("CO_PC");
                OnCO_PCChanged();
            }
        }
        private global::System.String _CO_PC;
        partial void OnCO_PCChanging(global::System.String value);
        partial void OnCO_PCChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBProyectoModel", "FK_CO_LOG_SYS_CO_USUARIO1", "CO_USUARIO")]
        public CO_USUARIO CO_USUARIO_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CO_USUARIO>("DBProyectoModel.FK_CO_LOG_SYS_CO_USUARIO1", "CO_USUARIO").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CO_USUARIO>("DBProyectoModel.FK_CO_LOG_SYS_CO_USUARIO1", "CO_USUARIO").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<CO_USUARIO> CO_USUARIO_1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<CO_USUARIO>("DBProyectoModel.FK_CO_LOG_SYS_CO_USUARIO1", "CO_USUARIO");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<CO_USUARIO>("DBProyectoModel.FK_CO_LOG_SYS_CO_USUARIO1", "CO_USUARIO", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBProyectoModel", Name="CO_USUARIO")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class CO_USUARIO : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto CO_USUARIO.
        /// </summary>
        /// <param name="id">Valor inicial de la propiedad ID.</param>
        public static CO_USUARIO CreateCO_USUARIO(global::System.Int32 id)
        {
            CO_USUARIO cO_USUARIO = new CO_USUARIO();
            cO_USUARIO.ID = id;
            return cO_USUARIO;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ID
        {
            get
            {
                return _ID;
            }
            set
            {
                if (_ID != value)
                {
                    OnIDChanging(value);
                    ReportPropertyChanging("ID");
                    _ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ID");
                    OnIDChanged();
                }
            }
        }
        private global::System.Int32 _ID;
        partial void OnIDChanging(global::System.Int32 value);
        partial void OnIDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOGIN
        {
            get
            {
                return _LOGIN;
            }
            set
            {
                OnLOGINChanging(value);
                ReportPropertyChanging("LOGIN");
                _LOGIN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOGIN");
                OnLOGINChanged();
            }
        }
        private global::System.String _LOGIN;
        partial void OnLOGINChanging(global::System.String value);
        partial void OnLOGINChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PWD
        {
            get
            {
                return _PWD;
            }
            set
            {
                OnPWDChanging(value);
                ReportPropertyChanging("PWD");
                _PWD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PWD");
                OnPWDChanged();
            }
        }
        private global::System.String _PWD;
        partial void OnPWDChanging(global::System.String value);
        partial void OnPWDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DESCRIPCION
        {
            get
            {
                return _DESCRIPCION;
            }
            set
            {
                OnDESCRIPCIONChanging(value);
                ReportPropertyChanging("DESCRIPCION");
                _DESCRIPCION = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DESCRIPCION");
                OnDESCRIPCIONChanged();
            }
        }
        private global::System.String _DESCRIPCION;
        partial void OnDESCRIPCIONChanging(global::System.String value);
        partial void OnDESCRIPCIONChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String NOMBRES
        {
            get
            {
                return _NOMBRES;
            }
            set
            {
                OnNOMBRESChanging(value);
                ReportPropertyChanging("NOMBRES");
                _NOMBRES = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("NOMBRES");
                OnNOMBRESChanged();
            }
        }
        private global::System.String _NOMBRES;
        partial void OnNOMBRESChanging(global::System.String value);
        partial void OnNOMBRESChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ESTADO
        {
            get
            {
                return _ESTADO;
            }
            set
            {
                OnESTADOChanging(value);
                ReportPropertyChanging("ESTADO");
                _ESTADO = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ESTADO");
                OnESTADOChanged();
            }
        }
        private Nullable<global::System.Int32> _ESTADO;
        partial void OnESTADOChanging(Nullable<global::System.Int32> value);
        partial void OnESTADOChanged();

        #endregion
    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("DBProyectoModel", "FK_CO_LOG_SYS_CO_USUARIO1", "CO_LOG_SYS")]
        public EntityCollection<CO_LOG_SYS> CO_LOG_SYS_1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<CO_LOG_SYS>("DBProyectoModel.FK_CO_LOG_SYS_CO_USUARIO1", "CO_LOG_SYS");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<CO_LOG_SYS>("DBProyectoModel.FK_CO_LOG_SYS_CO_USUARIO1", "CO_LOG_SYS", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DBProyectoModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto sysdiagrams.
        /// </summary>
        /// <param name="name">Valor inicial de la propiedad name.</param>
        /// <param name="principal_id">Valor inicial de la propiedad principal_id.</param>
        /// <param name="diagram_id">Valor inicial de la propiedad diagram_id.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }

    #endregion
    
}
